---
- name: intall and start nginx
  hosts: all
  become: true


  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Fix broken dependencies
      command: apt --fix-broken install -y
      ignore_errors: yes
      register: fix_broken_result

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
